### ISSUE TITLE
Don't overwrite HTTP_HOST with HTTP_X_FORWARDED_HOST

### ISSUE THREAD

**Issue by proligde** [chameleon-system/chameleon-system#330]
**Describe the bug**
In index.php $_SERVER['HTTP_HOST'] (The hostname provided by the webserver) is overwritten with $_SERVER['HTTP_X_FORWARDED_HOST'] (The hostname(s) of the forwarding proxies/hosts provided by the webserver).

This is not ok, since HTTP_HOST contains only a single hostname while HTTP_X_FORWARDED_HOST can contain multiple. comma-separated hostnames which leads to a crash/warning (see below)

**Affected version(s)**
all

**To Reproduce**
Chain two or more reverse proxies calling each other via hostname

**Expected behavior**
normal execution of the system

**Actual behavior**
the system crashes with

WARNING: [pool www] child 12 said into stderr: "#1 /usr/local/apache2/htdocs/releases/build-8/customer/vendor/chameleon-system/chameleon-base/src/CoreBundle/Service/Initializer/PortalDomainServiceInitializer.php(79): ChameleonSystem\CoreBundle\Service\Initializer\PortalDomainServiceInitializer->determinePortalAndDomainDefault(Object(Symfony\Component\HttpFoundation\Request), Object(ChameleonSystem\CoreBundle\Service\PortalDomainService))"

[22-Feb-2019 15:32:52] WARNING: [pool www] child 12 said into stderr: "#2 /usr/local/apache2/htdocs/releases/build-8/customer/vendor/chameleon-system/chameleon-base/src/CoreBundle/Service/PortalDomainService.php(115): in /usr/local/apache2/htdocs/releases/build-8/customer/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php on line 120"

**Comment by umulmrum** [comment]
I did some research, but couldn't find out why we added this (those lines have been around since at least 2012). So yes, we should consider removing.
